name: connectars
description: This package is developed to create a single executable and run it as a websocket server.
  This server would be only a proxy server between client and api.
version: 0.2.4
homepage: https://github.com/yakupars/connectars

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
